name: DevOps / Security

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: [main]
  schedule:
    - cron: "0 5 25-31 * 0" # last Sunday of month, 05:00 UTC

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  security-fs:
    if: ${{ !github.event.pull_request.draft }}
    permissions:
      contents: read
      actions: read
      security-events: write
    uses: FelipeFuhr/ffreis-workflows-general/.github/workflows/general-security-fs.yml@ef5f76c297dba0d2990210a905d045c826092427 # v1.4.3
    with:
      working-directory: "."
      scan-history: true
      upload-sarif: false
